config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"
  resources :articles do
    resources :comments, only: [:create, :destroy, :update, :edit] do
      get :reply
    end
  end

  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  belongs_to :user


  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :replies, class_name: "Comment", foreign_key: "parent_id", dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  belongs_to :parent, class_name: "Comment", optional: true
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  enum :user_type, [:user, :admin]
  
  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :email, :password, :password_confirmation, :user_type)
    end
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: :back)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to root_path, notice: "Article created succesfully"
    else
      flash[:alert] = @article.errors.full_messages.first
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to root_path, notice: "Article Edited Successfully"
    else
      flash[:alert] = @article.errors.full_messages.first
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other, notice: "Article Deleted Successfully"
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :image)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article_and_comment, only: [:edit, :update, :destroy]
  before_action :set_article, only: [:create, :reply]

  def create
    @comment = @article.comments.build(comment_params)
    if @comment.save
      redirect_to @article, notice: 'Comment created successfully'
    end
  end

  def edit
  end

  def reply
    @parent_comment = @article.comments.find(params[:comment_id])
    @reply = Comment.new(article_id: @article, parent_id: @parent_comment)
  end

  def update
    if @comment.update(comment_params)
      redirect_to @article, notice: "Comment Edited Successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @comment.destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to @article
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body, :user_id, :parent_id)
  end
  
  def set_article_and_comment
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    authorize @comment
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    @like.save

    if like_params[:likeable_type] == "Comment"
      redirect_to @like.likeable.article
    else
      redirect_to root_path
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    likeable = @like.likeable
    @like.destroy

    if likeable.class.name == "Comment"
      redirect_to likeable.article
    else
      redirect_to root_path
    end
  end

  private
  
  def like_params
    params.require(:like).permit(:likeable_type, :likeable_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def likes_count(likeable)
    likeable.likes.count
  end

  def is_liked(likeable)
    current_user.likes.find_by(likeable: likeable)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/articles/_article.html.erb
<div class="card card-body my-1">
  <%# Article Card Body %>
  <h3 class="card-title"><%= article.title %></h3>
  <h5 class="card-text">Created by: <%= article.user.full_name %></h5>
  <p class="card-text"><small class="text-muted">Created on: <%= article.updated_at.strftime("%d %B, %Y") %></small></p>

  <%# Article Actions and Likes %>
  <div class="container py-2">
  <% if user_signed_in? %>
    <%= render "articles/buttons/article_buttons", article: article %>
    <%= render "shared/like_unlike", component: article, component_type: "Article" %>
    <%= likes_count article %>
  <% else %>
    <i class="bi bi-star"></i> <%= likes_count article %>
  <% end %>
  </div>
</div>

app/views/articles/_article_form.html.erb
<%= form_with model: article do | form | %>
  <div class="form-group">
    <%= form.label :title, class: "label"%>
    <%= form.text_field :title, autofocus: true, class: "form-control my-3", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: "label"%>
    <%= form.text_area :body, autofocus: true, class: "form-control my-3", rows: 5, required: true, minlength: "10" %>
  </div>

  <div class="form-group">
    <%= form.label :image, class: "label"%>
    <%= form.file_field :image, class: "form-control-file my-3" %>
  </div>
  
  <%= form.submit %>
<% end %>

app/views/articles/_comment.html.erb
<% if comment.id %>
<div class="card my-3">

  <%# Comment Body %>
  <div class="card-header"><%= comment.user.full_name %></div>
  <div class="card-body">
    <div class="card-text"><%= comment.body %></div>

  <%# Comment Actions and Likes %>
    <% if user_signed_in? %>
      <%= render "articles/buttons/comment_buttons", article: article, comment: comment %>
      <%= render "shared/like_unlike", component: comment, component_type: "Comment" %>
      <%= likes_count comment %>
    <% else %>
      <span><i class="bi bi-star"></i> <%= likes_count comment %></span>
    <% end %> 
  </div>
  
  <%# Comment Replies %>
  <% comment.replies.each do |reply| %>
    <div class="float-right mx-5"><%= render "comment", comment: reply, article: article %></div>
  <% end if comment.replies %>
</div>
<% end %>

app/views/articles/_comment_form.html.erb
<div class="form-group">
  <%= form.label :body, class: "label"%>
  <%= form.text_field :body, class: "form-control my-3", required: true %>
</div>

<%= form.submit "New Comment", class: "btn btn-primary" %>

app/views/articles/buttons/_article_buttons.html.erb
<%= link_to "Edit", edit_article_path(article), class: "btn btn-primary mx-1" %>
<%= link_to "Delete", article_path(article), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
}, class: "btn btn-primary mx-1" %>

app/views/articles/buttons/_comment_buttons.html.erb
<%= link_to "Delete", [comment.article, comment], data: {
  turbo_method: :delete,
  turbo_confirm: "Delete the comment?"
}, class: "btn btn-primary" %>

<%= link_to "Edit", edit_article_comment_path(article, comment), class: "btn btn-primary" %>
<%= link_to "Reply", article_comment_reply_path(article, comment), class: "btn btn-primary" %>

<!--
<%= render "shared/modal_button", modal_button: "Edit", model_type: Article.new %>
<%= render "shared/modal_button", modal_button: "Reply", model_type: Article.new %>
-->

app/views/articles/edit.html.erb
<div class="container" data-turbo="false">
  <h2>Edit Article</h2>
  <%= render "article_form", article: @article %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>
  <% @articles.each do |article| %>
    <%= link_to render("article", article: article), article_path(article), class: "text-decoration-none text-reset" %>
  <% end %> 
  <%= link_to "Create New Article", new_article_path, class: "btn btn-info" if user_signed_in? %>
</div>

app/views/articles/new.html.erb
<div class="container" data-turbo="false">
  <h2>New Article</h2>
  <%= render "article_form", article: @article %>
</div>

app/views/articles/show.html.erb
<article class="card container p-3">
  <%# Article Body %>
  <h1><%= @article.title %></h1>
  <%= image_tag @article.image, class: "rounded img-fluid" if @article.image.attached? %>
  <section class="mt-3"><%= @article.body %></section>

  <%# Comment Form %>
  <div class="my-3">
    <h1 class="text-center">Comments</h1>
    <%= form_with model: [@article, @article.comments.build] do |form|%>
      <%= render "shared/comment_form", form: form %>
    <% end if user_signed_in? %>
    
  <%# Comments %>
    <div class="comments container">
      <% @article.comments.each do |comment| %>
        <%= render 'comment', comment: comment, article: @article unless comment.parent_id %>
      <% end %>
    </div>
  </div>
</article>

app/views/comments/edit.html.erb
<%= form_with model: [@article, @comment] do |form| %>
  <%= render "shared/comment_form", form: form %>
<% end %>

app/views/comments/reply.html.erb
<%= form_with model: [@article, @reply] do |form| %>
  <div class="form-group">
    <%= form.label :body, class: "label" %>
    <%= form.text_area :body, class: "form-control", required: true %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <%= form.hidden_field :parent_id, value: @parent_comment.id %>
  <%= form.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark px-4 py-2">
  <%= link_to "Blogu", root_path, class: "navbar-brand" %>
  <ul class="navbar-nav">
    <div class="d-flex">
    <% if user_signed_in? %>
      <li class="nav-item mx-2 btn btn-warning"><%= current_user.full_name %></li>
      <li class="nav-item"><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary" %> </li>
    <% else %>
      <li class="nav-item mx-2"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %></li>
      <li class="nav-item mx-2"><%= link_to "Login", new_user_session_path, class: "btn btn-secondary" %></li>
    <% end %>
    </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
      @import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css");
    </style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container p-5">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/shared/_comment_form.html.erb
<div class="form-group">
  <%= form.label :body, class: "label"%>
  <%= form.text_field :body, class: "form-control my-3", required: true %>
  <%= form.hidden_field :user_id, value: current_user.id %>
</div>

<%= form.submit "New Comment", class: "btn btn-primary" %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="btn" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="btn" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="btn" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="btn" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_like_button.html.erb
<%= form_with(model: Like.new, method: :post, class: "d-inline") do |form|%>
  <%= form.hidden_field :likeable_id, value: likeable[:id] %>
  <%= form.hidden_field :likeable_type, value: likeable[:type] %>
  <%= button_tag type: 'submit', class: "p-0 m-0 border-0 bg-white" do %>
    <i class="fs-4 bi bi-hand-thumbs-up"></i>
  <% end %>
<% end %> 

app/views/shared/_like_unlike.html.erb
<% if is_liked(component) %>
  <%= render "shared/unlike_button", like: is_liked(component) %>
<% else %>
  <%= render "shared/like_button", likeable: {id: component.id, type: component_type}%>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: Article.new  do |form| %>
          <%= form.label :body, class: "label" %>
          <%= form.text_field :body, class: "form-control my-3", required: true %>
          <%= form.hidden_field :user_id, value: current_user.id %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_button.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  <%= modal_button %>
</button>

app/views/shared/_unlike_button.html.erb
<%= link_to '<i class="fs-4 bi bi-hand-thumbs-up-fill"></i>'.html_safe, like_path(like), :method => :delete %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>